/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.sms.gui;

import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.apache.log4j.Logger;

/**
 *
 * @author andh
 */
public class Help extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(Help.class);
    
    /**
     * Creates new form Help
     * @param parent
     * @param modal
     */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);

        try {
            AssemblyInfo assemblyInfo = new AssemblyInfo();
            assemblyInfo.load();
            
            StyledDocument doc = jTextPane1.getStyledDocument();
            Style style = jTextPane1.addStyle("Styled", null);
            
            
            StyleConstants.setFontFamily(style, "Tahoma");
            StyleConstants.setFontSize(style, 16);
            StyleConstants.setBold(style, true); 
            insertLine(doc,style, assemblyInfo.getProduct().toUpperCase());
            
            StyleConstants.setBold(style, false); 
            StyleConstants.setFontSize(style, 14);
            insertString(doc, style, "Company: ");
            StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getCompany());
            
            
            // StyleConstants.setBold(style, true); 
            // StyleConstants.setBold(style, true); 
            insertString(doc, style, "Version: ");
            // StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getVersion());
            
            // StyleConstants.setBold(style, true); 
            insertString(doc, style, "Built-Date: ");
            // StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getBuildDate());
            
            
            // StyleConstants.setBold(style, true); 
            insertString(doc, style, "Built-By: ");
            // StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getBuildBy());
            
            
            // StyleConstants.setBold(style, true); 
            insertString(doc, style, "JDK: ");
            // StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getCreateBy());
            
            // StyleConstants.setBold(style, true); 
            insertString(doc, style, "Code-Revision: ");
            // StyleConstants.setBold(style, false); 
            insertLine(doc, style, assemblyInfo.getSvnRevision());
            
            // StyleConstants.setForeground(style, Color.red);

        } catch (Exception ex) {
            this.jTextPane1.setText("Cannot load assembly info");
        }
    }
    
    private void insertString(StyledDocument doc, Style style, String value) {
        try {
            doc.insertString(doc.getLength(), value, style);
        } catch (BadLocationException e) {
            logger.error(e.getMessage());
        }
    }
    private void insertLine(StyledDocument doc, Style style, String value) {
        try {
            doc.insertString(doc.getLength(), value + "\n", style);
        } catch (BadLocationException e) {
            logger.error(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setResizable(false);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Help dialog = new Help(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
